# Generated by Django 2.1.2 on 2019-02-27 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimport',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label__in': ['basedata', 'organ', 'auth']}, on_delete=models.SET('basedata'), to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='business_domain',
            field=models.CharField(choices=[('HR', '人事'), ('FI', '财务'), ('AD', '行政'), ('MA', '市场'), ('BU', '商务'), ('CS', '客服'), ('OT', '其他'), ('PO', '采购')], default='OT', max_length=4, verbose_name='business domain'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, choices=[('1', '名誉博士 '), ('2', '博士'), ('3', '硕士'), ('4', '学士'), ('5', '双学士'), ('9', '其他')], default='4', max_length=2, null=True, verbose_name='major degree'),
        ),
        migrations.AlterField(
            model_name='education',
            name='edu_type',
            field=models.CharField(choices=[('10', '研究生教育'), ('20', '大学本科教育'), ('30', '大学专科教育'), ('40', '中等职业教育'), ('60', '普通高级中学教育'), ('70', '初级中学教育'), ('80', '小学教育'), ('90', '其他'), ('99', '非学历教育')], default='1', max_length=2, verbose_name='edu type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(blank=True, choices=[('10', '经营者'), ('20', '中层管理人员'), ('21', '一般管理人员'), ('30', '专业技术人员'), ('40', '技能人员'), ('50', '服务人员'), ('90', '其他人员')], default='21', max_length=2, null=True, verbose_name='employ category'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, choices=[('CN', '中国'), ('EG', '埃及'), ('AT', '奥地利'), ('AU', '澳大利亚'), ('PK', '巴基斯坦'), ('BR', '巴西'), ('KP', '北朝鲜'), ('BE', '比利时'), ('IS', '冰岛'), ('PL', '波兰'), ('DK', '丹麦'), ('DE', '德国'), ('FR', '法国'), ('KR', '韩国'), ('NL', '荷兰'), ('CA', '加拿大'), ('US', '美国'), ('JP', '日本'), ('TW', '中国台湾'), ('HK', '中国香港'), ('ES', '西班牙'), ('GR', '希腊'), ('SG', '新加坡'), ('NZ', '新西兰'), ('IT', '意大利'), ('GB', '英国'), ('MO', '中国澳门'), ('IL', '以色列')], default='CN', max_length=2, null=True, verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='degree',
            field=models.CharField(blank=True, choices=[('1', '名誉博士 '), ('2', '博士'), ('3', '硕士'), ('4', '学士'), ('5', '双学士'), ('9', '其他')], default='4', max_length=2, null=True, verbose_name='major degree'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('0', '未知的性别'), ('1', '男性'), ('2', '女性'), ('9', '未说明的性别')], default='1', max_length=2, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='health',
            field=models.CharField(blank=True, choices=[('1', '健康或良好'), ('2', '一般或较弱'), ('3', '有慢性病（一）'), ('4', '有慢性病（二）'), ('6', '残疾'), ('7', '军残')], default='1', max_length=2, null=True, verbose_name='health'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='literacy',
            field=models.CharField(blank=True, choices=[('0', '研究生'), ('10', '大学本科'), ('20', '大学专科和专科学校'), ('40', '技工学校'), ('50', '高中'), ('60', '初中'), ('70', '小学'), ('80', '文盲或半文盲')], default='10', max_length=2, null=True, verbose_name='literacy'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='major',
            field=models.CharField(blank=True, choices=[('01', '哲学'), ('02', '经济学'), ('03', '法学'), ('04', '教育学'), ('05', '文学'), ('06', '历史学'), ('07', '理学'), ('08', '工学'), ('09', '农学'), ('10', '医学'), ('11', '军事学'), ('12', '管理学'), ('14', '建筑学'), ('99', '其他')], default='99', max_length=2, null=True, verbose_name='major type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital',
            field=models.CharField(blank=True, choices=[('10', '未婚'), ('20', '初婚'), ('21', '再婚'), ('22', '复婚'), ('30', '丧偶'), ('40', '离婚'), ('90', '其他')], default='10', max_length=2, null=True, verbose_name='marital status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nation',
            field=models.CharField(blank=True, choices=[('01', '汉族'), ('02', '蒙古族'), ('03', '回族'), ('04', '藏族'), ('05', '维吾尔族'), ('06', '苗族'), ('07', '彝族'), ('08', '壮族'), ('09', '布依族'), ('10', '朝鲜族'), ('11', '满族')], default='01', max_length=2, null=True, verbose_name='nation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='party',
            field=models.CharField(blank=True, choices=[('01', '中国共产党党员'), ('02', '中国共产党预备党员'), ('03', '中国共产主义青年团团员'), ('04', '中国国民党革命委员会会员'), ('05', '中国民主同盟盟员'), ('06', '中国民主建国会会员'), ('07', '中国民主促进会会员'), ('08', '中国农工民主党党员'), ('09', '中国致公党党员'), ('10', '九三学社社员'), ('11', '台湾民主自治同盟盟员'), ('12', '无党派民主人士'), ('13', '群众')], default='13', max_length=2, null=True, verbose_name='political party'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.CharField(choices=[('10', '领导班子'), ('11', '副总师（助理）'), ('12', '部门负责人（正职）'), ('13', '部门负责人（副职）'), ('14', '部门内设机构负责人（正职）'), ('15', '部门内设机构负责人（副职）'), ('20', '一级职员'), ('21', '二级职员'), ('22', '三级职员'), ('23', '四级职员'), ('24', '五级职员'), ('25', '六级职员'), ('26', '七级职员'), ('27', '八级职员')], default='00', max_length=2, verbose_name='employee rank'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, choices=[('00', '无宗教信仰'), ('10', '佛教'), ('20', '喇嘛教'), ('30', '道教'), ('40', '天主教'), ('50', '基督教'), ('70', '东正教'), ('80', '伊斯兰教'), ('99', '其他')], default='00', max_length=2, null=True, verbose_name='religion'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='spjob',
            field=models.CharField(blank=True, choices=[('00', '非特殊工种'), ('11', '汽机运行值班工'), ('12', '锅炉运行值班工'), ('13', '燃料运行值班工'), ('14', '锅炉本体检修工'), ('15', '保温工'), ('16', '钢球磨煤机及制粉系统检修工'), ('17', '水轮机检修工'), ('6', '其他（由地方社会保障部门认可的特殊工种）'), ('21', '锅炉本体安装工'), ('22', '管道安装工'), ('23', '筑炉瓦工'), ('24', '装模工'), ('31', '水轮机安装工'), ('32', '采石工'), ('33', '爆破'), ('34', '石料粉碎工'), ('35', '潜水员'), ('35', '轮机工'), ('37', '水手'), ('41', '翻砂铸造工'), ('42', '喷砂工'), ('43', '镀锌工'), ('44', '电镀工'), ('45', '印刷线路制板工'), ('46', '浸漆工'), ('47', '电焊条制作工'), ('48', '注塑工'), ('49', '铆工'), ('51', '混凝土工'), ('52', '钢筋工'), ('53', '架子工'), ('54', '推土机司机'), ('55', '挖土机司机'), ('56', '重型载重汽车司机'), ('57', '野外勘测工'), ('58', '沥青工'), ('59', '环氧树脂工')], default='00', max_length=2, null=True, verbose_name='special job'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('10', '在岗工作'), ('11', '见习期（试用）'), ('12', '待岗'), ('20', '离职'), ('21', '退休'), ('22', '终止劳动合同'), ('23', '协商解除劳动合同'), ('24', '劳动者主张解除劳动合同'), ('25', '用人单位主张解除劳动合同'), ('30', '死亡')], default='10', max_length=2, null=True, verbose_name='employ status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag1',
            field=models.CharField(blank=True, choices=[('15', '复员干部'), ('10', '军转干部'), ('20', '转业士官'), ('30', '复员士官'), ('40', '退役士兵'), ('99', '非复转军人')], default='99', max_length=2, null=True, verbose_name='tag1 fzjr'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag2',
            field=models.CharField(blank=True, choices=[('1', '党委（党组）书记'), ('2', '党委（党组）副书记'), ('3', '党委常委（党组成员）'), ('4', '纪委书记（纪检组组长）'), ('6', '工会主席'), ('8', '其他党委（党组）负责人'), ('9', '非党委负责人')], default='9', max_length=2, null=True, verbose_name='tag2 dwld'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag3',
            field=models.CharField(blank=True, choices=[('010101', '董事长'), ('010102', '副董事长'), ('010103', '董事'), ('010104', '职工董事'), ('0201', '监事会主席'), ('0202', '监事会副主席'), ('0203', '监事'), ('0204', '国资委派出监事'), ('0205', '职工监事'), ('00', '非董事监事')], default='00', max_length=2, null=True, verbose_name='tag3 dsjs'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tag4',
            field=models.CharField(blank=True, choices=[('0', '未服兵役'), ('1', '退出现役'), ('2', '士兵预备役'), ('3', '军官预备役'), ('4', '服现役'), ('9', '其他')], default='0', max_length=2, null=True, verbose_name='tag4 byzk'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ygxs',
            field=models.CharField(blank=True, choices=[('1', '劳动合同制（长期）'), ('2', '劳动合同制（短期）'), ('3', '人事代理制'), ('4', '劳务派遣制'), ('5', '非全日制'), ('6', '业务外包'), ('9', '其他')], default='2', max_length=2, null=True, verbose_name='employ ygxs'),
        ),
        migrations.AlterField(
            model_name='family',
            name='relation',
            field=models.CharField(blank=True, choices=[('11', '丈夫'), ('12', '妻子'), ('21', '独生子'), ('22', '长子'), ('23', '次子'), ('24', '三子'), ('25', '四子'), ('26', '五子'), ('27', '养子或继子'), ('28', '女婿'), ('31', '独生女'), ('32', '长女'), ('33', '次女'), ('34', '三女'), ('35', '四女'), ('36', '五女'), ('37', '养女或继女'), ('51', '父亲'), ('52', '母亲'), ('53', '公公'), ('54', '婆婆'), ('55', '岳父'), ('56', '岳母'), ('57', '继父或养父'), ('58', '继母或养母'), ('71', '兄'), ('72', '嫂'), ('73', '弟'), ('74', '弟媳'), ('75', '姐姐'), ('76', '姐夫'), ('77', '妹妹'), ('78', '妹夫')], max_length=2, null=True, verbose_name='family title'),
        ),
        migrations.AlterField(
            model_name='family',
            name='status',
            field=models.CharField(blank=True, choices=[('11', '国家公务员'), ('13', '专业技术人员'), ('17', '职员'), ('21', '企业管理人员'), ('24', '工人'), ('27', '农民'), ('31', '学生'), ('37', '现役军人'), ('51', '自由职业者'), ('54', '个人经营者'), ('70', '无业人员'), ('80', '退（离）休人员'), ('90', '其他')], default='17', max_length=2, null=True, verbose_name='social status'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tp',
            field=models.CharField(blank=True, choices=[('10', '生产物料'), ('20', '建筑物/培训室'), ('30', '员工宿舍'), ('40', '工卡/饭卡'), ('50', '车辆'), ('60', '图书'), ('70', '工位'), ('80', '工单服务'), ('11', '办公用品')], default='10', max_length=2, null=True, verbose_name='mt type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'partner_type': 'C'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Partner', verbose_name='partner'),
        ),
        migrations.AlterField(
            model_name='valuelist',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='locked by'),
        ),
    ]
