# Generated by Django 2.1.2 on 2019-02-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syscfg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='syscfg.Module', verbose_name='module'),
        ),
        migrations.AlterField(
            model_name='role',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syscfg.Role', verbose_name='parent'),
        ),
    ]
