# Generated by Django 2.1.2 on 2019-02-27 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustitem',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.Inventory', verbose_name='inventory material'),
        ),
        migrations.AlterField(
            model_name='adjustitem',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.WareAdjust'),
        ),
        migrations.AlterField(
            model_name='initem',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.StockIn'),
        ),
        migrations.AlterField(
            model_name='initem',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.POItem', verbose_name='po item'),
        ),
        migrations.AlterField(
            model_name='initialinventory',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='initialinventory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='inititem',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.InitialInventory'),
        ),
        migrations.AlterField(
            model_name='inoutdetail',
            name='material',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_virtual': '0'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='inoutdetail',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Measure', verbose_name='measure'),
        ),
        migrations.AlterField(
            model_name='inoutdetail',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Warehouse', verbose_name='warehouse'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Measure', verbose_name='measure'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Warehouse', verbose_name='warehouse'),
        ),
        migrations.AlterField(
            model_name='outitem',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.Inventory', verbose_name='inventory material'),
        ),
        migrations.AlterField(
            model_name='outitem',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.StockOut'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.WareReturn'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='out_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.OutItem', verbose_name='out item'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='po',
            field=models.ForeignKey(blank=True, limit_choices_to={'entry_status': '0'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.PurchaseOrder', verbose_name='purchase order'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Warehouse', verbose_name='warehouse'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='out user'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selfhelp.WorkOrder', verbose_name='work order'),
        ),
        migrations.AlterField(
            model_name='wareadjust',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='wareadjust',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='out user'),
        ),
        migrations.AlterField(
            model_name='warereturn',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='warereturn',
            name='out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.StockOut', verbose_name='StockOut'),
        ),
        migrations.AlterField(
            model_name='warereturn',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='out user'),
        ),
    ]
