# Generated by Django 2.1.2 on 2019-02-27 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.OfferSheet'),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='material',
            field=models.ForeignKey(blank=True, limit_choices_to={'can_sale': '1', 'is_virtual': '0'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Measure', verbose_name='measure'),
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='tax',
            field=models.CharField(choices=[('0.00', '0%'), ('0.03', '3%'), ('0.05', '5%'), ('0.07', '7%'), ('0.10', '10%'), ('0.17', '17%')], default='0.00', max_length=6, verbose_name='tax rate'),
        ),
        migrations.AlterField(
            model_name='offersheet',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='offersheet',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'partner_type': 'C'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Partner', verbose_name='partner'),
        ),
        migrations.AlterField(
            model_name='offersheet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='offer man'),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.BankAccount', verbose_name='bank account'),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Partner', verbose_name='partner'),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='so',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.SaleOrder', verbose_name='sale order'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.SaleOrder'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='material',
            field=models.ForeignKey(blank=True, limit_choices_to={'can_sale': '1', 'is_virtual': '0'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Measure', verbose_name='measure'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='tax',
            field=models.CharField(choices=[('0.00', '0%'), ('0.03', '3%'), ('0.05', '5%'), ('0.07', '7%'), ('0.10', '10%'), ('0.17', '17%')], default='0.00', max_length=6, verbose_name='tax rate'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='invoice_type',
            field=models.CharField(choices=[('10', '普通发票'), ('20', '增值税专用发票'), ('30', '专业发票')], default='10', max_length=6, verbose_name='invoice type'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'partner_type': 'C'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Partner', verbose_name='partner'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='sales man'),
        ),
    ]
