# Generated by Django 2.1.2 on 2019-02-27 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfhelp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selfhelp.Activity', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='room',
            field=models.ForeignKey(blank=True, limit_choices_to={'tp': 20}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Material', verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='selfhelp.Activity'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='selfhelp.Activity'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selfhelp.Loan', verbose_name='loan record'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ.OrgUnit', verbose_name='cost center'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selfhelp.WorkOrder', verbose_name='work order'),
        ),
        migrations.AlterField(
            model_name='reimbursementitem',
            name='expense_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.ExpenseAccount', verbose_name='expenses account'),
        ),
        migrations.AlterField(
            model_name='reimbursementitem',
            name='reimbursement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='selfhelp.Reimbursement', verbose_name='reimbursement'),
        ),
        migrations.AlterField(
            model_name='woextravalue',
            name='param_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.ExtraParam', verbose_name='extra param'),
        ),
        migrations.AlterField(
            model_name='woextravalue',
            name='workorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='selfhelp.WorkOrder', verbose_name='workorder'),
        ),
        migrations.AlterField(
            model_name='woitem',
            name='material',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_virtual': '0'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='woitem',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Measure', verbose_name='measure'),
        ),
        migrations.AlterField(
            model_name='woitem',
            name='workorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='selfhelp.WorkOrder', verbose_name='workorder'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='business_domain',
            field=models.CharField(choices=[('HR', '人事'), ('FI', '财务'), ('AD', '行政'), ('MA', '市场'), ('BU', '商务'), ('CS', '客服'), ('OT', '其他'), ('PO', '采购')], default='OT', max_length=4, verbose_name='business domain'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='classification',
            field=models.CharField(choices=[('S', '内部服务'), ('R', '设备维修'), ('Q', '问题咨询'), ('D', '采购申请')], default='D', max_length=4, verbose_name='classification'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='refer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selfhelp.WorkOrder', verbose_name='refer wo'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='service',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_virtual': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.Material', verbose_name='service name'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', '新建'), ('SCHE', '调度'), ('PROC', '处理'), ('CLOSE', '关闭')], default='NEW', max_length=6, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
